name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjkxMGEyZTUtZTg0Zi00YzY4LWEzZGItZWE2NTQzM2IxYjI1IiwidGVuYW50X2lkIjoiZmU0ZWI0Y2FjMzM0MGE1NmY1NjVjYjNmYzZkNDcyZDY1MjFjOGJiYjdhMmUwNGI4OWZlMjhmZGU5ODI0MTYyMyIsImludGVybmFsX3NlY3JldCI6ImQ2MzkyNTMyLTZiNWMtNGIzYS05MzRmLTU5NmU2YmJlZjVlMCJ9.LNCli0Va-aB1Zpb98ASF9wUO2xXOtDb_1FP6RK5czno"
JWT_SECRET = "harshkaran"